version: '3'
services:
  postgres:
    container_name: postgre-db
    image: postgres
    hostname: postgre
    ports:
      - "6543:5432"
    environment:
      POSTGRES_USER: postgre
      POSTGRES_PASSWORD: postgre
      POSTGRES_DB: express
    volumes:
      - postgre-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    container_name: pgAdmin
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.ru
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped

  mongodb:
      image: mongo:5.0
      ports:
        - 27017:27017
      volumes:
        - ~/apps/mongo:/data/db
      environment:
        - MONGO_INITDB_ROOT_USERNAME=mongo
        - MONGO_INITDB_ROOT_PASSWORD=mongo

volumes:
  postgres-data: